name: Create Release

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  create_release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Extract Version Name
      run: |
        version=`perl -ne 'print "$&" if /(?<=version\s=\s\").*(?=\"\n)/' < Cargo.toml`
        versionName="v$version"
        releaseName="Release - $versionName"
        export VERSION=$version
        export VERSION_NAME=$versionName
        export RELEASE_NAME=$releaseName
        echo "Determined version name=$versionName"
        echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
        echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
    - uses: ncipollo/release-action@v1
      with:
        body: "See CHANGELOG.md for latest release notes"
        commit: main
        tag: ${{ env.VERSION_NAME }}
        name: ${{ env.RELEASE_NAME }}
        token: ${{ secrets.GITHUB_TOKEN }}
